import { useState } from "react";

function MainPage() {
  return (
    <>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
      <h1>THIS IS MAIN PAGE</h1>
    </>
  );
}

export default MainPage;
